### ISSUE TITLE
Version requirement stops install on 9.2.1

### ISSUE THREAD

**Issue by ngm** [pluginsGLPI/treeview#12]
This line in setup stops the plugin being installed on Glpi 9.2.1:

https://github.com/pluginsGLPI/treeview/blob/master/setup.php#L115

If you change the condition, e.g. to just

    if (version_compare(GLPI_VERSION, '9.1', 'lt')) {

you can install the plugin and it seems to work fine on 9.2.1.

**Comment by TrueBrujah** [comment]
This Workaround work patially because after installation 

If you go Administration ­> Profiles ­­> Super-Admin > Arborescence 

You got this message 

Fatal error: Uncaught Error: Call to undefined method Profile::dropdownNoneReadWrite() in /var/www/html/glpi/plugins/treeview/inc/profile.class.php:107 Stack trace: #0 /var/www/html/glpi/plugins/treeview/inc/profile.class.php(147): PluginTreeviewProfile->showForm('4') #1 /var/www/html/glpi/inc/commonglpi.class.php(482): PluginTreeviewProfile::displayTabContentForItem(Object(Profile), '1', '') #2 /var/www/html/glpi/ajax/common.tabs.php(96): CommonGLPI::displayStandardTab(Object(Profile), 'PluginTreeviewP...', '', Array) #3 {main} thrown in /var/www/html/glpi/plugins/treeview/inc/profile.class.php on line 107

**Comment by cedric-anne** [comment]
Hi,

Should have been fixed in 1.8.0.

Regards
